# Generated by Django 5.1.1 on 2024-11-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_alter_events_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='task_id',
            field=models.IntegerField(blank=True, help_text='task_id из балансира', null=True),
        ),
    ]
