# Generated by Django 5.1.1 on 2024-09-26 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('current_state', models.CharField(default=None, max_length=110, unique=True, verbose_name='К какому состоянию привязана?')),
                ('next_state', models.BooleanField(default=False, verbose_name='Ожидается ли изменение состояния на ввод')),
                ('handler', models.CharField(max_length=255, verbose_name='Имя функции обработчика')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(unique=True, verbose_name='ID Telegram')),
                ('first_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Фамилия пользователя')),
                ('username', models.CharField(blank=True, max_length=250, null=True, verbose_name='Username пользователя')),
                ('language', models.CharField(blank=True, max_length=250, null=True, verbose_name='Язык пользователя')),
                ('premium', models.BooleanField(blank=True, default=False, null=True, verbose_name='Имеет ли пользователь премиум-аккаунт')),
                ('state', models.CharField(help_text='Состояние', max_length=255)),
            ],
            options={
                'verbose_name': 'Пользователь бота',
                'verbose_name_plural': 'Пользователи бота',
            },
        ),
        migrations.CreateModel(
            name='TelegramBotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(max_length=100)),
                ('is_activ', models.BooleanField(default=False, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Токен',
                'verbose_name_plural': 'Токены',
            },
        ),
        migrations.CreateModel(
            name='Bot_Commands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст команды')),
                ('trigger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_commands', to='bot.bot_message', verbose_name='Связанное сообщение')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='Bot_Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст кнопки')),
                ('data', models.JSONField(default=dict, verbose_name='JSON объект')),
                ('message_trigger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_triggered', to='bot.bot_message', verbose_name='Связанное сообщение')),
            ],
            options={
                'verbose_name': 'Кнопку',
                'verbose_name_plural': 'Кнопки',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACCEPTED', 'Событие создано'), ('COMPLETED', 'Событие закончено')], max_length=110)),
                ('update_data', models.JSONField(default=dict, verbose_name='JSON объект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bot.botuser')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
