# Generated by Django 5.1.1 on 2024-10-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_bot_message_next_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot_message',
            name='handler',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Имя функции обработчика'),
        ),
    ]
