# Generated by Django 5.1.1 on 2024-11-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_bot_message_handler'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot_message',
            name='anyway_link',
            field=models.CharField(blank=True, help_text='На какое состояние пебрасывает пользователя', max_length=110, null=True, unique=True),
        ),
    ]
