# Generated by Django 5.1.1 on 2024-12-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_bot_message_anyway_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='photo',
            field=models.FileField(blank=True, default=' ', null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='prompt',
            field=models.TextField(blank=True, default=' ', help_text='Состояние', null=True),
        ),
    ]
