# Generated by Django 5.1.1 on 2024-12-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_botuser_photo_botuser_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='gender',
            field=models.CharField(blank=True, help_text='Гендер', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='interes',
            field=models.CharField(blank=True, help_text='Интерес', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='period',
            field=models.CharField(blank=True, help_text='Период', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='summa',
            field=models.CharField(blank=True, help_text='Сумма инвестиций', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='type_investor',
            field=models.CharField(blank=True, help_text='Тип инвестора', max_length=255, null=True),
        ),
    ]
