# Generated by Django 5.1.1 on 2024-12-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_botuser_gender_botuser_interes_botuser_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='format_photo',
            field=models.CharField(blank=True, help_text='Формат', max_length=255, null=True),
        ),
    ]
