# Generated by Django 5.1.1 on 2024-12-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_botuser_last_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='last_photo_path',
            field=models.TextField(blank=True, help_text='Путь до посл фото', null=True),
        ),
    ]
