# Generated by Django 5.1.1 on 2024-12-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_remove_botuser_last_photo_path_botuser_men_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='photo_count',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='promt_number',
        ),
        migrations.AddField(
            model_name='botuser',
            name='negative_prompt',
            field=models.TextField(blank=True, null=True, verbose_name='Негативный Промт'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='promt',
            field=models.TextField(blank=True, null=True, verbose_name='Промт'),
        ),
    ]
