# Generated by Django 5.1.1 on 2024-12-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_remove_botuser_photo_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='men',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='now_num',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='promt',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='women',
        ),
        migrations.AddField(
            model_name='botuser',
            name='prompt_leonardo',
            field=models.TextField(blank=True, null=True, verbose_name='Промт для leonardo'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='prompt',
            field=models.TextField(blank=True, default=' ', help_text='Промт', null=True),
        ),
    ]
