# Generated by Django 5.1.1 on 2024-12-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_remove_botuser_men_remove_botuser_now_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='gender_first',
            field=models.CharField(blank=True, help_text='Гендер первый раз', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='interes_first',
            field=models.CharField(blank=True, help_text='Интерес первый раз', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='period_first',
            field=models.CharField(blank=True, help_text='Период первый раз', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='summa_first',
            field=models.CharField(blank=True, help_text='Сумма инвестиций первый раз', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='type_investor_first',
            field=models.CharField(blank=True, help_text='Тип инвестора первый раз', max_length=255, null=True),
        ),
    ]
