# Generated by Django 5.1.1 on 2024-12-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_botuser_gender_first_botuser_interes_first_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='count_generation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
