# Generated by Django 5.1.1 on 2024-12-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_remove_botuser_count_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='count_generation',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
